### PR TITLE
First draft of the interview with Gabor.

### PR DESCRIPTION
**Pull request by manwar**
Hi @briandfoy @dnmfarrell 

Please review the first draft.

I have requested Gabor for his photo in Portrait format. As soon I receive, I will update the interview.

I am planning a big announce of the launch interview on Perl Weekly newsletter to be published on 1st June 2020 as I am also editing the next edition. It would be great if you could please find some time in your busy schedule. Apology for late notice.  

It is absolutely fine, if it can't make it this week. We can definitely aim for the following week.

Many Thanks.

Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by dnmfarrell** [comment]
Hey @manwar this looks great, thank you.

Yes the main thing is getting a landscape-oriented picture of the interviewee (a minimum of 800px wide, 1200px and up would be better though, with a height approximately 50-70% of the width).

If Gabor can't provide that, we can still take a square image and use it as the article thumbnail though. I can handle the editing of the photo and get this interview published in time for Perl weekly.

**Comment by briandfoy** [comment]
I've already mentioned to Mohammad that we'll space this out a little to give Dave Cross's interview some air to breath. Two weeks from now seems like a good time to publish.

**Comment by manwar** [comment]
How about 15th June 2020? @dnmfarrell @briandfoy

**Comment by briandfoy** [comment]
I think the article is mostly good. There's not much editing to do in the interview format because what they answered is what they answered. I did adjust some punctuation and a few other details, and strengthened the intro a little. You can adjust a bit more based on what I did—it's in the same branch name here . You can pull that into your local clone if you like, then recommit to your same local branch and the updates should show up in this PR automatically. https://github.com/tpf/perldotcom/tree/the-perl-ambassador-gabor-szabo

**Comment by manwar** [comment]
@briandfoy I have merged your changes and pushed it.

**Comment by briandfoy** [comment]
Things look good. Get that photo of Gabor and we can have this ready for next week.

**Comment by manwar** [comment]
Sure, will do.

**Comment by manwar** [comment]
@briandfoy just pushed the Gabor photo.
I have re-based it before pushing the changes.
Please review it.

**Comment by manwar** [comment]
Hi @briandfoy, @dnmfarrell,

I am preparing the Perl Weekly newsletter for early morning release tomorrow. 
Can I please get the link  to the launch interview to be included in the newsletter?

Many Thanks.

Best Regards,
Mohammad

**Comment by briandfoy** [comment]
David is going through the final review on this and will published it when he's done. Remember that we are volunteers and fit this in when we can.

**Comment by dnmfarrell** [comment]
Hey @manwar the image of Gabor appears to be squashed do you have the original?

**Comment by manwar** [comment]
> Hey @manwar the image of Gabor appears to be squashed do you have the original?

Hi @dnmfarrell , I just forwarded you the email from Gabor with original photo.

**Comment by dnmfarrell** [comment]
Am releasing this now. This was my bad - I didn't see your message yesterday and was planning on releasing it today. The article looks good, thanks!

**Comment by manwar** [comment]
Thanks @dnmfarrell @briandfoy for releasing the launch interview.

**Pull request merged**
