### PR TITLE
Add an article about ot, a file opening utility written in Perl

### PR DESCRIPTION
**Pull request by oalders**
I'm actually not sure how this renders as I'm having issues with Hugo.  It looks good in MacDown, though.  If this isn't suitable for perl.com, that's not a problem.  I can always post this on my own site, but I figured I'd try here first.  :)

### CODE REVIEW

**Comment by dnmfarrell** [comment]
Hey @oalders this looks great, thank you!

I reviewed the article and pushed some small edits to a [branch](/tpf/perldotcom/commits/oalders-open-this). Would you mind taking a look and seeing if you agree with the changes or not?

**Comment by oalders** [comment]
Hi @dnmfarrell,

Thanks so much for taking the time to edit my article.  So much quoting.  :)  Let me know if there's anything else you may need.  I really do appreciate the work you've put into this.  It looks great.

**Comment by dnmfarrell** [comment]
Sure thing, the article was in great shape, especially considering you couldn't view it in a browser. Thanks again for contributing :+1:

**Comment by dnmfarrell** [comment]
It's live https://www.perl.com/article/how-do-i-open-this-/ :tada:

**Pull request merged**
