### PR TITLE
A tour with Net::FTP + Thibault Duponchelle author datas

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
Hello,

I propose this article about installing an ftp server and discovering with Net::FTP.

It's based on my personal experience using it, but I created simpler code snippets for the need of this article.

If you're are OK with the theme of this article, it would be nice to test again the code snippets (if you don't want to do, ask me then and I will test before publishing).  

I tested the code blocks recently (maybe 2 months ago).

Maybe the first sentences are too "politic" (light critics...), we can remove if necessary.

You can change everything you want, I'm not the best Perl dev on this planet neither a professional writer and even less a native English speaker :grin: 

I wait for your feedback to know if this kind of article can fit in perl.com 

Regards.

Thibault

### CODE REVIEW

**Comment by briandfoy** [comment]
This looks good, and I'll work on it this week to clean up a few things. We have a couple articles ahead of you so this might work for the end of June. Thanks!

**Comment by briandfoy** [comment]
Hey @thibaultduponchelle, I was able to go through the article. Things look good and I made some light edits for style. Not a big deal. I did play with the big code at the end and refactored out the FTP login stuff to a sub, so you may want to adjust that. See my branch in this repo (https://github.com/tpf/perldotcom/tree/thibault/new_article) and pull that into your repo and merge it how you like (although really, with this sort of stuff, merges are weird).

One thing that could really help the article is a personal story from you about a project where this saved time and money, or something like that.

And yeah, I don't mind naming S3. Was that the slow and complex service you had in mind? :)

I'm looking at having this ready for the end of the month, so if we had all the adjustments done around a week before that, David could have a final pass before publishing it.

**Comment by thibaultduponchelle** [comment]
Hello @briandfoy 

Thank you a lot for the review and changes :smiley: 

I added the story, it's very long, maybe we can drop it and keep a small paragraph. I let you decide, take what you want. And it will make you some more edits.

I added some edits on top of yours because I don't liked too much the appearance (I like to have paragraphs with just a bit more carriage returns and emphasizing).

Anothing thing, FYI on my local machine `[Net::FTP]({{</* mcpan "Net::FTP" */>}}` does not translate into anything (but I left them as is as I trust your changes). 

And it was not S3, but I kept it (even if I don't know S3) :D

Rgds.

Thibault

**Comment by briandfoy** [comment]
Can we back off on the typographical styling? We'd like most of the articles on Perl.com to look the same, which is why I combined some paragraphs and took out most of the interior bold. Instead of worrying about appearance, which we'll handle, we'd like you to focus on content.

**Comment by thibaultduponchelle** [comment]
> Can we back off on the typographical styling? We'd like most of the articles on Perl.com to look the same, which is why I combined some paragraphs and took out most of the interior bold. Instead of worrying about appearance, which we'll handle, we'd like you to focus on content.

Yes, no problem we can back off. I thought it would help actually (sorry about that then).

About content, is there anything else I need to do ?

**Comment by thibaultduponchelle** [comment]
I just pushed a commit to back off the typographical styling

**Comment by thibaultduponchelle** [comment]
I added it on your recommendation but I'm not sure if that (too) long story about unrelated topic really serve the article. Maybe we can shorten it to few sentences about the need of having an anonymous and reliable way to backup file. 

Something like : 
At $work I have to carry on an army of developers that create customized build pipelines from handcrafted configuration files.
It is a lot of support to help them to create this file according to the messy spec, and we were blind when we wanted to help failing pipeline creation/build (no way to retrieve configuration from workspace).
I get the idea to backup and centralize automatically the configuration file during the creation of the build pipeline workspace.
It was intended to help both developers (configuration "samples") and support (see history, versioned then we can check diffs, replay).
The constraints where to be able to exchange file from various places with variable users.
The FTP protocol was a perfect fit and proved later to require ZERO support.

What do you think about it ?

**Comment by briandfoy** [comment]
Just an update. You've probably noticed that we just published a Perl 7 article. That caught us a bit by surprise, so we're going to push your article in the middle of July. Not a big deal.

**Comment by thibaultduponchelle** [comment]
OK, no problem, no hurry :)

**Comment by briandfoy** [comment]
These recent edits look good. I plan on getting back to some Perl.com business on Monday and you article is first in the queue.

**Comment by thibaultduponchelle** [comment]
Great :+1:

**Comment by briandfoy** [comment]
I'm going to merge this now as a draft and then edit it.

**Comment by briandfoy** [comment]
I made very slight edits. Everything looks really good. Now David will do the final pass on it, choose the publication date, and so on. See the linked issue right above this comment (#246).

**Comment by thibaultduponchelle** [comment]
Great thank you :+1:

**Pull request merged**
