### PR TITLE
Interview with Dave Cross about Perl Hacks

### PR DESCRIPTION
**Pull request by briandfoy**

### CODE REVIEW

**Comment by dnmfarrell** [comment]
What an interesting article, thanks! @davorg do you have a picture of yourself we could use for the article?

**Comment by davorg** [comment]
How's this one?

dave_2017

**Comment by dnmfarrell** [comment]
Pretty good - do you have it in a landscape format? Else I can make it the article thumbnail but leave the image at the top of the article blank.

**Comment by davorg** [comment]
Tell me what size you want and I'll crop it (or something similar) appropriately.

**Comment by dnmfarrell** [comment]
Great, a minimum of 800px wide (1200px and up would be better though), with a height approximately 50-70% of the width.

**Comment by davorg** [comment]
dave_2017_landscape

**Pull request merged**
