### PR TITLE
Addressing issue 255: "Investigate broken MetaCPAN links"

### PR DESCRIPTION
**Pull request by jonasbn**
- https://metacpan.org/pod/Apache::AuthenHook pointing to newer development release
- https://metacpan.org/pod/Apache::AxKit::Language::XSP::SimpleTaglib N/A
- https://metacpan.org/pod/Apache::AxKit::Language::XSP::TaglibHelper N/A
- https://metacpan.org/pod/Apache::Clean pointing to newer development release
- https://metacpan.org/pod/Apache::Peek N/A
- https://metacpan.org/pod/App::duckpan Bad casing in URL
- https://metacpan.org/pod/App::single N/A
- https://metacpan.org/pod/AutoCRUD N/A
- https://metacpan.org/pod/AxKit::XS::Util N/A
- https://metacpan.org/pod/Business::US::USPS::WebTools OK
- https://metacpan.org/pod/Cache::Memory::Simple::ID N/A
- https://metacpan.org/pod/Catalyst::Example::Controller::InstantCRUD pointing to release
- https://metacpan.org/pod/Couchbase::README pointed to distribution instead of component in distribution
- https://metacpan.org/pod/DB::DataStore N/A
- https://metacpan.org/pod/Device::BusPirate::Chip::DS1307 pointed to renamed distribution
- https://metacpan.org/pod/Device::BusPirate::Chip::SSD1306 pointed to renamed distribution
- https://metacpan.org/pod/distribution/App-ucpan/script/ucpan pointing to release
- https://metacpan.org/pod/GraphViz2::Marpa::Lexer::DFA N/A, does not seem to be included in distribution any longer
- https://metacpan.org/pod/GraphViz2:Marpa::Lexer::DFA N/A, does not seem to be included in distribution any longer
- https://metacpan.org/pod/Java::Swing pointing to release
- https://metacpan.org/pod/Keystone N/A perhaps Alien Keystone
- https://metacpan.org/pod/Language::Prolog::SWI N/A
- https://metacpan.org/pod/Lavoco::Website pointing to release
- https://metacpan.org/pod/Lib::Pcap I think this is an error in the article, it should perhaps reference Net::Pcap as the code does
- https://metacpan.org/pod/Marpa::HTML pointing to release
- https://metacpan.org/pod/Message::String N/A
- https://metacpan.org/pod/Mojo::Cloudflare N/A available on GitHub though
- https://metacpan.org/pod/Mojo::IOLoop::HoboProcess N/A
- https://metacpan.org/pod/Mojo::UserAgent::UnixSocket N/A available on GitHub though
- https://metacpan.org/pod/Mojolicious::Plugin::PayPal pointing to release
- https://metacpan.org/pod/Mojolicious::Plugin::Responsinator N/A
- https://metacpan.org/pod/MooX::Prototype N/A
- https://metacpan.org/pod/PDL::Transform::Color N/A perhaps auto generated code ?
- https://metacpan.org/pod/RestrictionDigest pointed to release
- https://metacpan.org/pod/RJBS/CPAN-Uploader-0.103004/bin/cpan-upload updated link to release
- https://metacpan.org/pod/Test::Countlib N/A
- https://metacpan.org/pod/Win32::GuiTest::Examples pointed to release

### CODE REVIEW

**Comment by jonasbn** [comment]
Please let me now if the approach should be different, else please use my contriibution to addressing issue #255 as you see fit.

**Comment by briandfoy** [comment]
Let me think about this. We probably should note when some of these modules are not in the current releases or something similar.

**Comment by jonasbn** [comment]
Hi @briandfoy 

Just let me know and I will give it another _spin_

**Comment by briandfoy** [comment]
I have not forgotten about this. I need to work on a few other perl.com things and I can get back to this. I want to clear up this issue and the related issues this month.

**Review by briandfoy — APPROVED** [review]
This looks good. Thanks!

**Pull request merged**
