### PR TITLE
Article: "Observing Coronavirus Pandemic with Raku"

### PR DESCRIPTION
**Pull request by ash**

### CODE REVIEW

**Comment by ash** [comment]
Added.

**Comment by dnmfarrell** [comment]
@ash thank you for the timely contribution, I think our readers will get a blast out of this.

I proof-read the article and pushed some edits to the branch [ash-master](/tpf/perldotcom/commits/ash-master). Could you take a look, and if you agree with them, merge them into this PR?

Thanks!

**Comment by ash** [comment]
@dnmfarrell thank you, the changes look really great. I made a small corrections. here's the pull request: https://github.com/tpf/perldotcom/pull/231.

There's one thing where I did not understand what was your idea here https://github.com/tpf/perldotcom/commit/c4107b24d7b5e06a34dac08ddf76051fa4d40c95#diff-a1f40813fdb52c9676b86812cb4d3b7bR20. Either 'It's a great tool for" or "It's great at". 

The rest is awesome.

**Comment by dnmfarrell** [comment]
Hey @ash 
I agree with your suggestions; I've made the changes in the branch. Thanks!

**Pull request merged**
