### PR TITLE
#208 - CGI Book Cover

### PR DESCRIPTION
**Pull request by jacoby**
You will want to crop, but here it is.

### CODE REVIEW

**Comment by briandfoy** [comment]
Can you grab the cover from O'Reilly? They have links to large versions of their book covers:

http://shop.oreilly.com/product/9781565924192.do

**Comment by jacoby** [comment]
Don't like my picture? I'm thinking a used and slightly damaged cover shows the state of CGI, but not my call.

**Comment by briandfoy** [comment]
I don't think many people will make that connection, and I think they will wonder why we didn't have a better image.

**Comment by dnmfarrell** [comment]
Thanks for this @jacoby - after thinking about it, I think just deleting the article cover image might be best. It's not related to any CGI book, so whatever book image we put there risks being associated with the article.

**Pull request closed without merging**
