### PR TITLE
A Perl love letter

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
Hello,

FYI, I initially named this "Why I love Perl" before to rename to "A Perl love letter". Both titles seems fine.

I hope this article will fit well into perl.com

Regards.

Thibault

### CODE REVIEW

**Comment by briandfoy** [comment]
This could be the start of something interesting. Here are my suggestions:

* Choose three of those item and expand on them. Use concrete, extended examples and personal stories.
* Examine if your statements are actually true. Is CPAN really a collection of all of human knowledge with the best software for every domain? I think you'd rightfully get a lot of pushback from that assertion. Examples can help.
* Avoid broad generalizations: "Very very smart and nice people, no trolls, no crying babies. Newcomers refrain to ask too much before searching and veterans are very helpful." Really? That's a generalization that I don't you can support. The Perl community is a community like any other. Perhaps a story about how someone helped you (or you helped someone) would refine your point.

**Comment by thibaultduponchelle** [comment]
I understand your suggestions, especially the one about broad generalizations. 
This is a very positive and personal point of view, despite being not completely true for sure but this is also why I use "I" pronoun.
I thought it was not a problem to be a bit over too positive, and Perl folks are nice, don't you think ? :smile: 

I think the current blog post is too far from being acceptable then I will close this one and try to come back with something maybe more "factual".

Thank you for the rereading and remarks :+1: :grinning:

**Comment by briandfoy** [comment]
Personal opinion is fine. But for anything that you state, whether in an opinion piece or a tech article, you should support it somehow. Remember that many, many people will read this and they have their own thoughts on everything you do, from where you put your braces to which language you should be using. Your job as the author is to anticipate these things and account for them.

Some folks are nice, and some aren't. But, if you imply as a rule that they all are nice, people easily defeat your argument and discount your entire article. Not only that, you are implicitly saying that other language communities don't have these things, which is also not true. For example, I think you could easily replace "Perl" with "Python" (with the other minor adjustments to go with that, like Flask instead of Mojo) and have an article that is just as true. When you make these statements, consider the converse too. What really sets Perl apart?

Remember that being overly positive is untrustworthy. If you only see one side of things, your opinion isn't as valuable to as many people as it could be. You need balance and perspective.

**Comment by thibaultduponchelle** [comment]
Thank you for your valuable answer.

**Pull request closed without merging**
