### PR TITLE
Proposed article, second part of "How to become CPAN contributor" article.

### PR DESCRIPTION
**Pull request by manwar**
Hi @dnmfarrell 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by dnmfarrell** [comment]
Thanks @manwar, sorry for the delay, I was on vacation. I'll get to this soon.

**Comment by dnmfarrell** [comment]
It's nice when things come in threes: @manwar do you have a third example (license, strict/warnings, ...).

Do you know if KWALITEE flags strict when a module uses Moose but does not `use strict;`?

**Comment by manwar** [comment]
HI @dnmfarrell 

Thanks for your comments.
I agree with you about "three".
I will add some more to make it worth reading.

Best Regards,
Mohammad S Anwar

**Comment by manwar** [comment]
Hi @dnmfarrell 

Please review the changes.
I have added 2 more examples to the article.

Many Thanks.
Best Regards,
Mohammad S Anwar

**Comment by dnmfarrell** [comment]
Thanks for the submission @manwar! I'll merge and open a branch for editing.

**Pull request merged**
