### PR TITLE
First draft of interview with Damian Conway.

### PR DESCRIPTION
**Pull request by manwar**
Hi @briandfoy / @dnmfarrell 

Please review the draft of interview with Damian Conway.
I have also attached the raw image as received.

Many Thanks.

Best Regards,
Mohammad

### CODE REVIEW

**Comment by briandfoy** [comment]
Somehow you got Curtis's interview in this pull request. Can you fix that?

**Comment by manwar** [comment]
@briandfoy I have cleaned up the branch. 
sorry for the inconvenience.

**Review by briandfoy — APPROVED** [review]

**Comment by briandfoy** [comment]
This is merged. edited, and in master. I have it scheduled for next week sometime.

**Comment by manwar** [comment]
> This is merged. edited, and in master. I have it scheduled for next week sometime.

Thanks @briandfoy

**Pull request merged**
