### PR TITLE
Bang Bang article

### PR DESCRIPTION
**Pull request by briandfoy**

### CODE REVIEW

**Comment by briandfoy** [comment]
@ thibaultduponchelle Check the edits I've made. If you agree with them, I'd like to schedule this for next week.

**Comment by thibaultduponchelle** [comment]
Hello,

First thank you a lot for all the edits :+1: 

We need to edit the python script to make it python 3 compatible (add ( ) to print should be enough). 
Second, why perl -x-ception was totally removed ?

**Comment by briandfoy** [comment]
I'll handle the Python 3 issue.

We can put back the `-x-ception` section, but I think you need to tighten it up and decide which point you'd like to make. I think you were going a long way to get a very small pay-off and the "exception" pun doesn't work. It was also near the end of the article and not leading to anything, so I didn't know how to integrate it into the article. 

For what it's worth, only about a quarter of the stuff I write for an article makes it into a final result, no matter how much I like it. :)

**Comment by thibaultduponchelle** [comment]
I opened a PR towards this branch were I propose a new version of the paragraph. Tell me what do you think about it :)

**Comment by briandfoy** [comment]
@thibaultduponchelle - I've incorporated your edits. Let me know if we can publish the result. Thanks,

**Comment by thibaultduponchelle** [comment]
I have just some minor edits (opened a PR for it) and we're done :+1: 

After merging, you can publish :)

**Comment by briandfoy** [comment]
This article is live!

**Comment by thibaultduponchelle** [comment]
Great ! 

I noticed very 2 small issues. First I made a mistake when I updated the `perl -c` and this is the correct output (the name of the script is wrong). 
```
$ perl -c i-am-python.pl 
syntax error at i-am-python.pl line 3, near "import time"
i-am-python.pl had compilation errors.
```

Second the MetaCPAN links are not resolved at the end of the article.

I'm very satisfied with this article and the work we have made :) Thank you.

**Comment by briandfoy** [comment]
I've fixed those issues. It might take a bit to update.

**Pull request closed without merging**
