### PR TITLE
Added new basic tutorial describing common Perl symbols.

### PR DESCRIPTION
**Pull request by dgilder**

### CODE REVIEW

**Comment by briandfoy** [comment]
There are a few improvements you can make here to clear up beginner confusion.

* The sigils don't mark variable types and we shouldn't emphaisize that. They tell you how you are treating thingys: 

    * A `$` means single item (scalar variable, or single element access to a container). 
    * A `@` means multiple elements (array, or array or hash slice)
    * A `%` means keys and values (hash, or array or hash chunk slicing)
    * The `#` has a few exceptions, like `@#array`

* Some examples with the postfix dereference would be nice.

**Comment by dnmfarrell** [comment]
Thanks for the submission!

**Comment by dgilder** [comment]
Thanks Brian, I was running into the 1,000 word guideline so I didn’t go into references, `->`,  and more complicated uses of @ and %.   I figured that might be better as a detailed followup article (including things like hash slices).

I’ll update the descriptions about what is actually going on with the sigils, I was trying to keep it simple, and loosely based on the perldata docs, but I probably oversimplified.  I also didn’t want to go into "variable names” vs the more proper term “identifier", but it may be useful to make that distinction as well.

Good point on $#, are there any other # exceptions you can think of off the top of your head?  Looks like 1.#INF might be one.  I might just mention $# as the most common example of # not meaning comment.

I also just realized David has an article `On Sigils` that might be a useful followup link.

**Comment by briandfoy** [comment]
I wouldn't worry too much about the 1,000 word limit if you aren't wasting words. :)

**Comment by briandfoy** [comment]
It's been a few months and this hasn't progressed so I'm closing it. If you refine the article just send another pull request.

**Pull request closed without merging**
