### PR TITLE
138 cgi and perl

### PR DESCRIPTION
**Pull request by jacoby**
This needs a little work. The opening could be stronger and the closing less abrupt.

But rather than let this hang, I'll throw this into the editorial process.

### CODE REVIEW

**Comment by dnmfarrell** [comment]
Thanks for this @jacoby ! I'll review it tonight

**Comment by dnmfarrell** [comment]
Thanks for putting this together @jacoby, I think you've got some gems in here.  I've had a read through and have some feedback:

* the tags in the frontmatter need to be quoted else the JSON parse fails
* This article is long. We aim for up to 1,000 words, and it's almost double that! Some topics like: the history of CGI, its removal from core, CGI programming in bash, Rails' release are interesting, but lengthen the article without advancing the article's main purpose. Removing them will sharpen the focus of the remaining content.
* Consider adding some personal context - give it some flavor! Share an anecdote or tell a story about your experience with CGI. A single sentence could be enough. The intro is often an easy place for this. E.G. "At work we still use CGI for tasks such as ...".
* Its structure is a non-linear tarantino-esque style (e.g. starting at the end) - this can be simplified! What about:
  1. What is CGI
  1. Processing input (e.g. a form submission)
  1. Generating HTML (why not to do it with CGI, TT example)
  1. Configuring CGI on a web server
  1. Why not to use CGI (limitations, alternatives)
  1. Useful CGI references (articles, books, modules, documentation that might help users)

I think you have most of this already. Would you be willing to try and restructure the article to something like the above outline?

Thanks!

**Comment by jacoby** [comment]
Absolutely.

**Comment by jacoby** [comment]
OK, I have it down to 1260, plus the header. I don't know what to pull without removing sections....

**Comment by dnmfarrell** [comment]
Hey @jacoby this is taking shape! I've merged the article, will open a branch with some edits for your approval

**Comment by jacoby** [comment]
:+1:

**Comment by Leont** [comment]
Not to be unappreciative of your efforts, but why are we doing this?

As a community we've been trying to move people away from CGI and especially CGI.pm. Even its own documentation mentions 

> CGI.pm is no longer considered good practice for developing web applications, including quick prototyping and small web scripts. There are far better, cleaner, quicker, easier, safer, more scalable, more extensible, more modern alternatives available at this point in time. These will be documented with [CGI::Alternatives](https://metacpan.org/pod/CGI::Alternatives).

This article looks like it comes 15 years too late. I can't think of a single reason where one would to actively choose CGI.pm over all of the many alternatives in 2018.

> The “good” parts of CGI.pm, the header creation and parameter parsing, are well-explained in the module’s documentation.

Plack supports both quite fine, actually.

**Comment by dnmfarrell** [comment]
@Leont it's part of our Google-popular Perl articles [project](https://github.com/tpf/perldotcom/projects)

**Comment by Leont** [comment]
That's doesn't make it desirable. I can understand an article about alternatives to CGI (a lot can be written about that). I can even understand an article about "maintaining legacy CGI.pm applications". But an article about new CGI development is a dead-end at best.

**Comment by dnmfarrell** [comment]
Well, we'll have to agree to disagree. Locking this thread now before it turns into r/perl.

**Pull request merged**
